### ISSUE TITLE
Implement Travis CI

### ISSUE THREAD

**Issue by hover2pi** [lkreidberg/batman#29]
Would it be possible to add Travis CI testing to this repo? We here at ExoCTK are trying to make `batman` a dependency for our exoplanet software but Travis builds fail when trying to install it, citing no `numpy` install. Thanks!

**Comment by lkreidberg** [comment]
Hmm, that surprises me because numpy is explicitly included as a dependency in the setup.py file for batman.

I've never used Travis, but I do know of a recent python package that uses it with C extensions. It's Rodrigo Luger's starry (https://github.com/rodluger/starry). I would recommend comparing the setup.py file from batman and starry and see if anything needs to be added.

**Comment by pcubillos** [comment]
Hi Laura, I think all you need is to setup a .travis.yml file, a requirements.txt file (in addition to what is specified in the setup.py requirements), and a tests/ folder to get travis CI running.
I've been dealing with this over the past weeks, so I have it pretty fresh in my head. Do you want me to prepare a PR with this? it wouldn't be much problem.

**Comment by lkreidberg** [comment]
@pcubillos that would be great!!!
