### ISSUE TITLE
Freeze during computation of the light-curve

### ISSUE THREAD

**Issue by odemangeon** [lkreidberg/batman#45]
I have encountered this problem quite a few time. It always happened when I try to fit a light-curve with batman using an MCMC. The code just freeze and seems to be stuck in an infinite loop. At the beginning I noticed that this tends to happens when the eccentricity gets high (typically 0,75 or higher). So I ignored the problem by preventing my eccentricity to go to high, but now I would like to let the eccentricity go high so I am trying to understand where this comes from. I first thought the planets orbit was crossing the stellar disk. It might have been the problem some times, but I am now making sure that it's not the case, yet code sometimes still gets stuck. So I am a bit out of ideas. I was wondering if this could be due to the initialization of the model, which is initialized with values that are too far for the ones explored by my MCMC (I usually initialize the model with dummy parameters values) ? I have recently faced this issue with the non-linear limb darkening model. I have also encountered the issue with the quadratic one,  but with the quadratic one I was not making sure that the planetary orbit doesn't cross the stellar surface.

I am trying to get a code that reproduces the error, but it's difficult, because the issue appears randomly during MCMC explorations (for which I often don't write on file the values taken by the parameters at each iteration as the code goes).

**Comment by odemangeon** [comment]
I managed to catch a freeze and record the parameters

```
import batman
import numpy as np

tt = np.array([2079.489153993809, 2079.4905428567663])

params = batman.TransitParams()
params.t0 = tt.mean()
params.per = 1.  
params.rp = 0.1 
params.a = 15. 
params.inc = 90.
params.ecc = 0. 
params.w = 90.
params.limb_dark = "nonlinear" 
params.u = [0.5, 0.1, 0.1, -0.1]

mod = batman.TransitModel(params, tt)

params.t0 = 1367.273421737073
params.per = 3.6906878266282113 
params.rp = 0.04091310616009109 
params.a = 94.86505638695871 
params.inc = 87.76256732660998 
params.ecc = 0.987357159319355 
params.w = -17.38895124449652 
params.u = [0.11538587433155638, 1.580603941225135, -1.4518646738768346, 0.5839716393696303, ]

mod.light_curve(params)
```
my version of batman is 2.4.6

**Comment by Christopher-Mann** [comment]
I'm encountering the same freezing issue as @odemangeon.  When I use multi-processing, it causes all cores to quit running, except for one which gets stuck at 100% CPU usage and never quits.  It doesn't even seem to be a process I can interrupt on my jupyter notebook.  I need to completely restart the kernel to get it working again.  

Strangely, even though I'm pretty sure the issue is with the `batman.TransitModel(params,t)` call, nothing above it in the cell will run if the parameters trigger the freeze.  I can't even print something at the top of the cell.

I have a minimally working example here:

```
import batman
import numpy as np
import matplotlib.pyplot as plt

params = batman.TransitParams()

params.t0  = 2.45840419e+06              
params.per = 9.16798122e+01           
params.rp  = 3.09679227e-02  
params.a   = 8.79036329e+01
params.ecc = 0.98                      ## <--- freeze only happens with certain e values near 0.98
params.w   = -114.29363793804626
params.inc = 90
params.limb_dark = "quadratic" 
params.u   = [ 0.303, 0.268  ]


npoints = 300 ## <--- 100, 200, 290, 299 are all fine.  300+ causes a freeze

t = np.linspace( params.t0-.5,params.t0+.5, npoints) 
m = batman.TransitModel(params,t) # initializes model
flux = m.light_curve(params)      # caclulates lightcurve

plt.plot(t,flux)
plt.show()
```

As far as I can tell, there appears to be some combination of `params.e` and `npoints` here that causes the crash.  With `e=0.98`, it runs smoothly if I initiate the model `t` array with <300 points.  However, the crash occurs if I choose `npoints=300` or greater.  I don't see any of these issues when `e` is a smaller value.  Interestingly, it also works fine when `e>0.99`, so it's not just _high_ `e` values, but something to do with the vicinity of `e=0.98`

I am also using version 2.4.6
