### ISSUE TITLE
Did nonlinear_ld get moved?

### ISSUE THREAD

**Issue by bmorris3** [lkreidberg/batman#8]
When I try to import the current build of batman I get: 
```python
In [1]: import batman
batma---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-bdd3f47826ab> in <module>()
----> 1 import batman

/astro/users/bmmorris/git/batman/batman/__init__.py in <module>()
      4 __version__ = "2.1.1"
      5 
----> 6 from .transitmodel import *
      7 from .tests import *
      8 from .plots import *

/astro/users/bmmorris/git/batman/batman/transitmodel.py in <module>()
     17 import numpy as np
     18 import matplotlib.pyplot as plt
---> 19 from . import _nonlinear_ld
     20 from . import _quadratic_ld
     21 from . import _uniform_ld

ImportError: cannot import name _nonlinear_ld
```

**Comment by bmorris3** [comment]
That was my bad, figured it out. Nevermind!

**Comment by eeconn** [comment]
What did the issue turn out to be? I'm seeing the same problem.

**Comment by bmorris3** [comment]
I'm not sure what the problem was, but I'm pretty sure I uninstalled and reinstalled batman and it worked again.

**Comment by eeconn** [comment]
Thanks. Turns out in my case the admin had downgraded numpy and scipy on the workstation I was using, so I had to go to a different machine.

On Jun 30, 2017 11:38, "Brett M. Morris" <notifications@github.com> wrote:

I'm not sure what the problem was, but I'm pretty sure I uninstalled and reinstalled batman and it worked again.
